import Head from "next/head";
import Image from "next/image";
import Avatar from "../components/Avatar";
import Footer from "../components/Footer";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import { useRef } from "react";
import { useRouter } from "next/dist/client/router";
export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;
    
    if(!term) return;

    router.push(`/search/?term=${term}`)
  };

  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-700">
        {/* Left Section */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        {/* Right Section */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>

          {/* Icon */}
          <ViewGridIcon className="viewgrid" />
          <Avatar url="https://yt3.ggpht.com/yti/APfAmoFV_G4Ix1hgko-tLXkyZdCGH-f9sqMWyOkedxOo=s88-c-k-c0x00ffffff-no-rj-mo" />
        </div>
      </header>
      {/* Body */}
      <form className="flex flex-col items-center mt-[135px] flex-grow w-4/5">
        <Image
          src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png"
          alt="google-image"
          height={100}
          width={300}
        />
        <div className="search-container">
          <SearchIcon className="search-icon" />
          <input type="text" className="input-field" ref={searchInputRef}></input>
          <MicrophoneIcon className="microphone-icon" />
        </div>
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="button">Google Search</button>
          <button onClick={search} className="button">I&apos;rem Feeling Lucky</button>
        </div>
      </form>

      {/* Footer */}
      <Footer />
    </div>
  );
}
